import type { Metadata } from "next";
import { Inter, Montserrat, Lato } from "next/font/google"; // Import semua font yang diperlukan
import "./globals.css";

// Daftar font yang digunakan
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"], // Tentukan berat font (400 = regular, 700 = bold)
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Maggot BSF Colomadu",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logos.svg", // atau bisa juga "/favicon.png" kalau kamu pakainya PNG
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${montserrat.variable} ${lato.variable}`} // Gunakan ketiga font ini
    >
      <body className="antialiased">{children}</body>
    </html>
  );
}
